DBMS/DBMS/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ase_project/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('homepage/',include('django.contrib.auth.urls')),
    path('',views.index,name='index'),
    path('homepage/',include('homepage.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
    path('finalapp/',include('finalapp.urls')),
    path('category_page/',include('category_page.urls')),
    path('myapp',include('myapp.urls')),
    path('feedback/',views.display_feedback,name='display_feedback')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

finalapp/urls.py
from django.urls import path, re_path
from . import views
urlpatterns = [
    path('',views.home,name="home"),
    path('upload/',views.model_form_upload,name='model_form_upload'),
    path('searchdata/',views.searchdata,name='searchdata')
]

myapp/urls.py
from django.urls import path
from myapp import views


app_name='myapp'

urlpatterns=[
     path('index/(?P<value>\s+)',views.index,name='index'),
    path('category',views.category,name='category')

]

finalapp/models.py
#from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from homepage.models import UserProfileInfo
# Create your models herUe.
class Document(models.Model):
    category_choices=(
    ('Objects','Objects'),
    ('Animals','Animals'),
    ('Abstract','Abstract'),
    ('Festivals','Festivals'),
    ('Food','Food'),
    ('Lifestyle','Lifestyle'),
    ('Nature','Nature'),
    ('People','People'),
    ('Architecture','Architecture'),
    ('Sports','Sports'),
    ('Fashion','Fashion'),
    )
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    name= models.CharField(max_length=150,default="")
    category= models.CharField(max_length=150,default="",choices=category_choices)
    image=models.ImageField(default='',upload_to='')
    uploaded_at=models.DateTimeField(auto_now_add=True)
    rating=models.IntegerField(default='5')
    total_image_downloads=models.IntegerField(default='0')
    #userid=models.OneToOneField(models1.UserProfileInfo,on_delete='CASCADE')
    #userid=FOREIGNKEY(UserProfileInfo,on_delete='CASCADE')
    #userid = models.ForeignKey(models1.UserProfileInfo,on_delete='CASCADE')

finalapp/forms.py
from django import forms

from .models import Document


class DocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('name','category','image')

finalapp/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db.models import Q
import os

from .models import Document
from .forms import DocumentForm
def home(request):
    return render(request, 'finalapp/home.html')

def model_form_upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            formInstance = form.save(commit=False)
            formInstance.user = request.user

            formInstance.save()
            return redirect('home')
    else:
        form = DocumentForm()
    return render(request, 'finalapp/model_form_upload.html', {
        'form': form
    })
def searchdata(request):
     if request.method=="GET":
         key=request.GET.get('searchword')
         #key2=request.GET.get('searchwordmain')
         searchedlist=Document.objects.filter(Q(category__icontains=key) | Q(name__icontains = key))
         #print(searcheddict)
         #x = Document.objects.filter(category__icontains=key)
         #print(x)
         #z = {**x,**searcheddict}
         #print(z)
         # if len(searcheddict)==0:
         #     searcheddict=Document.objects.filter(category__icontains=key)
         #searcheddict2=Document.objects.filter(name__icontains=key)
         #searcheddict2=Document.objects.filter(name__icontains=key2)
         items=[]

         #searchedlist=[]
         # for obj in queryset:
         #     if obj.name==key:
         #         print(obj.name)
         #for p in Document.objects.raw("SELECT * FROM finalapp_Document WHERE name LIKE key"):
         #  searchedlist.append(p)
         #  print(p.name)
         #print(settings.MEDIA_DIR)
         #for p in searcheddict:

            # x = str(p.image)
            # y = os.path.join(settings.MEDIA_DIR,x)
            #print(y)
            #listimages.append(y)
            #listimages.append(y)
            #print("df",listimages)
         #listimages = [w.replace('\\', '\') for w in listimages]
         #print(listimages)
         context={'items':searchedlist}

     return render(request,'myapp/category/index.html',context)

# Create your views here.

templates/finalapp/home.html
<!DOCTYPE html>
<body>

{% block content %}



      <a href="{% url 'model_form_upload' %}">Model Form Upload</a>


  
{% endblock %}
</body>
</html>

templates/finalapp/model_form_upload.html
<!doctype html>
<!--<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

</head>
<body>
{% block content %}


   <div class="card" style="width : 75rem">

<div class="card-body" style="width : 50rem;">

  <form method="post" enctype="multipart/form-data" class = "form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
</div>
</div>

{% endblock %}
</body>-->

<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>

<body>
  <!--<div class="container" style="background-image: url('https://media2.picsearch.com/is?dDWp_Bjz2jyuKwZHkdGM4NaEWTzB4mT9qCSMC_pVxXM&height=255');">
-->
<div class="container">
<center>


   <div class="card" style="width : 75%">

<div class="card-body" style="width : 50%;">



  <form method="post" enctype="multipart/form-data" class = "form-group">

    <input type="hidden" name="csrfmiddlewaretoken" value="yhyAa3xeMHtUSFj4qerUKTUQRDsF5sM1SoMwSSDvfJhOgk1DoJR0sUM1ezZMjQ7L">
    <label for="id_name">Name:</label> <input type="text" name="name" maxlength="150"  class = "form-control" required id="id_name">
<label for="id_category">Category:</label> <select name="category" id="id_category" class= "form-control">
  <option value="Objects">Objects</option>

  <option value="Animals">Animals</option>

  <option value="Abstract">Abstract</option>

  <option value="Festivals">Festivals</option>

  <option value="Food">Food</option>

  <option value="Lifestyle">Lifestyle</option>

  <option value="Nature">Nature</option>

  <option value="People">People</option>

</select>

<label for="id_image">Image:</label> <input type="file" name="image" accept="image/*" class= "form-control" required id="id_image">
{% csrf_token %}
  <br>
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>

</div>
</div>
</center>
</div>
</body>

templates/finalapp/searchdata.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>


<ul>
    {{searcheddict}}
<!--
    {% for key in searcheddict %}

      {{key}}
      <br>
      {% endfor %} -->
</ul>
  </body>
</html>